services:
  frontend:
    name: beer-tracker
    type: static
    root: client
    dockerfile: Dockerfile
    build:
      context: ./client
      dockerfile: Dockerfile
    publish:
      path: /usr/share/nginx/html
      port: 3000

